### ISSUE TITLE
Data Component Failure

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#106]
I have tried the first two tutorials (MNIST and Model from scratch).  Both of them fail on the data load similar to this thread where you stated that the data component was crashing- https://forum.perceptilabs.com/t/cant-get-gui-work/293.  The error is below:

Internal error in asyncio.events:88: Error in create_response
Traceback (most recent call last):
  File "perceptilabs\mainInterface.py", line 236, in perceptilabs.mainInterface.Interface.create_response
  File "perceptilabs\mainInterface.py", line 330, in perceptilabs.mainInterface.Interface._create_response
  File "perceptilabs\mainInterface.py", line 557, in perceptilabs.mainInterface.Interface._get_network_data
  File "perceptilabs\lwInterface.py", line 225, in perceptilabs.lwInterface.GetNetworkData.run
  File "perceptilabs\lwInterface.py", line 295, in perceptilabs.lwInterface.GetNetworkData._maybe_apply_autosettings
  File "perceptilabs\autosettings\base.py", line 62, in perceptilabs.autosettings.base.SettingsEngine.run
  File "perceptilabs\lwcore\base.py", line 54, in perceptilabs.lwcore.base.LightweightCore.run
  File "perceptilabs\lwcore\base.py", line 66, in perceptilabs.lwcore.base.LightweightCore._run_subgraph
  File "perceptilabs\lwcore\base.py", line 80, in perceptilabs.lwcore.base.LightweightCore._get_layer_results
  File "perceptilabs\lwcore\base.py", line 102, in perceptilabs.lwcore.base.LightweightCore._get_cached_result
  File "perceptilabs\graph\spec.py", line 101, in perceptilabs.graph.spec.GraphSpec.compute_field_hash
  File "perceptilabs\layers\specbase.py", line 141, in perceptilabs.layers.specbase.LayerSpec.compute_field_hash
AttributeError: 'DataRandomSpec' object has no attribute 'fields'

**Comment by Rolun** [comment]
Hi,

One of our dependencies got updated and started crashing the tool recently. A new version of PerceptiLabs has been released to fix this issue. If you upgrade to that one (pip install --upgrade perceptilabs) it should start working.
Hope this helps!

All the best,
Robert
