### ISSUE TITLE
Fault indication - Kernel is offline

### ISSUE THREAD

**Issue by WuDou2** [PerceptiLabs/PerceptiLabs#123]
Hi everybody, 
there is a strange error with the kernel communication / configuration ...

Does anyone have an idea why???

(perceptilabs) C:\Users\snake>perceptilabs -v=3 -> d:\output.txt
usage: perceptilabs [-h] [-v VERBOSITY]
perceptilabs: error: unrecognized arguments: -

(perceptilabs) C:\Users\snake>perceptilabs -v=3
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
PerceptiLabs: Starting
2021-03-22 11:19:22.432388: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-03-22 11:19:22.432616: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Performing system checks...

Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
March 22, 2021 - 11:19:24
Django version 3.1.6, using settings 'static_file_server.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CTRL-BREAK.
System check identified no issues (0 silenced).
March 22, 2021 - 11:19:25
Django version 3.1.6, using settings 'fileserver.settings'
Starting development server at http://127.0.0.1:8011/
Quit the server with CTRL-BREAK.
System check identified no issues (0 silenced).
March 22, 2021 - 11:19:25
Django version 3.1.6, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[22/Mar/2021 11:19:27] "GET /?token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 493
[22/Mar/2021 11:19:27] "GET /kernel_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:27] "GET /fileserver_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:27] "GET /rygg_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:29] "GET /?token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 493
[22/Mar/2021 11:19:29] "GET /fileserver_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:29] "GET /kernel_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:29] "GET /rygg_url HTTP/1.1" 200 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\a-tec\.conda\envs\perceptilabs\lib\site-packages\perceptilabs\__init__.py", line 1, in <module>
    from perceptilabs.mainServer import main
  File "perceptilabs\mainServer.py", line 29, in init perceptilabs.mainServer
AttributeError: module 'tensorflow' has no attribute 'disable_v2_behavior'
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
[22/Mar/2021 11:19:32] "GET /rygg_url HTTP/1.1" 200 0
[22/Mar/2021 11:19:32] "GET /version?token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 22
[22/Mar/2021 11:19:32] "HEAD /directories?path=D:/Perceptilabs//DigitalFireTest&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 45
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53141)
Traceback (most recent call last):
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
----------------------------------------
[22/Mar/2021 11:19:32] "GET /projects/ HTTP/1.1" 200 268
[22/Mar/2021 11:19:32] "GET /models/2/ HTTP/1.1" 200 219
[22/Mar/2021 11:19:32] "GET /models/3/ HTTP/1.1" 200 190
[22/Mar/2021 11:19:32] "GET /mixpanel/decide/?verbose=1&version=1&lib=web&token=1480b2244fdd4d821227a29e2637f922&ip=1&_=1616408372334 HTTP/1.1" 200 0
[22/Mar/2021 11:19:32] "GET /app/updates_available/ HTTP/1.1" 200 22
[22/Mar/2021 11:19:32] "GET /mixpanel/track/?data=eyJldmVudCI6ICJtcF9wYWdlX3ZpZXciLCJwcm9wZXJ0aWVzIjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkNocm9tZSIsIiRjdXJyZW50X3VybCI6ICJodHRwOi8vbG9jYWxob3N0OjgwODAvP3Rva2VuPVdOMF9sWFBtd1VhUzc5UGtwaEExNDBQeEMtajgxb0RhdW53WXpDUkRKSnMiLCIkYnJvd3Nlcl92ZXJzaW9uIjogODksIiRzY3JlZW5faGVpZ2h0IjogODY0LCIkc2NyZWVuX3dpZHRoIjogMTUzNiwibXBfbGliIjogIndlYiIsIiRsaWJfdmVyc2lvbiI6ICIyLjI5LjEiLCJ0aW1lIjogMTYxNjQwODM3Mi4zNDgsImRpc3RpbmN0X2lkIjogInVkby5waW9udGVrQHdlYi5kZSIsIiRkZXZpY2VfaWQiOiAiMTc4NTk1NTZmYTQzMWYtMDRmYmM3YzdhZDk2OGQtNWMzZjFkNGQtMTQ0MDAwLTE3ODU5NTU2ZmE1NGE1IiwiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIiR1c2VyX2lkIjogInVkby5waW9udGVrQHdlYi5kZSIsIm1wX3BhZ2UiOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgwLz90b2tlbj1XTjBfbFhQbXdVYVM3OVBrcGhBMTQwUHhDLWo4MW9EYXVud1l6Q1JESkpzIiwibXBfYnJvd3NlciI6ICJDaHJvbWUiLCJtcF9wbGF0Zm9ybSI6ICJXaW5kb3dzIiwidG9rZW4iOiAiMTQ4MGIyMjQ0ZmRkNGQ4MjEyMjdhMjllMjYzN2Y5MjIifX0%3D&ip=1&_=1616408372349 HTTP/1.1" 200 0
[22/Mar/2021 11:19:32] "GET /mixpanel/track/?data=eyJldmVudCI6ICIkb3B0X2luIiwicHJvcGVydGllcyI6IHsiJG9zIjogIldpbmRvd3MiLCIkYnJvd3NlciI6ICJDaHJvbWUiLCIkY3VycmVudF91cmwiOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgwLz90b2tlbj1XTjBfbFhQbXdVYVM3OVBrcGhBMTQwUHhDLWo4MW9EYXVud1l6Q1JESkpzIiwiJGJyb3dzZXJfdmVyc2lvbiI6IDg5LCIkc2NyZWVuX2hlaWdodCI6IDg2NCwiJHNjcmVlbl93aWR0aCI6IDE1MzYsIm1wX2xpYiI6ICJ3ZWIiLCIkbGliX3ZlcnNpb24iOiAiMi4yOS4xIiwidGltZSI6IDE2MTY0MDgzNzIuMzU0LCJkaXN0aW5jdF9pZCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCIkZGV2aWNlX2lkIjogIjE3ODU5NTU2ZmE0MzFmLTA0ZmJjN2M3YWQ5NjhkLTVjM2YxZDRkLTE0NDAwMC0xNzg1OTU1NmZhNTRhNSIsIiRpbml0aWFsX3JlZmVycmVyIjogIiRkaXJlY3QiLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogIiRkaXJlY3QiLCIkdXNlcl9pZCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCJ0b2tlbiI6ICIxNDgwYjIyNDRmZGQ0ZDgyMTIyN2EyOWUyNjM3ZjkyMiJ9fQ%3D%3D&ip=1&_=1616408372355 HTTP/1.1" 200 0
[22/Mar/2021 11:19:32] "HEAD /directories?path=D:/NumPy/&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 21
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53157)
[22/Mar/2021 11:19:32] "GET /json_models?path=D:/Perceptilabs//DigitalFireTest/model.json&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 44916
Traceback (most recent call last):
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
[22/Mar/2021 11:19:32] "GET /json_models?path=D:/NumPy//model.json&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 292432
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
----------------------------------------
[22/Mar/2021 11:19:32] "GET /json_models?path=D:/Perceptilabs//DigitalFireTest/model.json&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 44916
[22/Mar/2021 11:19:32] "GET /json_models?path=D:/NumPy//model.json&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 292432
[22/Mar/2021 11:19:33] "HEAD /directories?path=D:/Perceptilabs//DigitalFireTest&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 45
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53162)
Traceback (most recent call last):
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
[22/Mar/2021 11:19:33] "POST /json_models?path=D:/Perceptilabs//DigitalFireTest&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 57
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
[22/Mar/2021 11:19:33] "HEAD /directories?path=D:/NumPy/&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 21
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53166)
Traceback (most recent call last):
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
----------------------------------------
[22/Mar/2021 11:19:33] "POST /json_models?path=D:/NumPy/&token=WN0_lXPmwUaS79PkphA140PxC-j81oDaunwYzCRDJJs HTTP/1.1" 200 33
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
[22/Mar/2021 11:19:37] "GET /mixpanel/engage/?data=eyIkc2V0IjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkNocm9tZSIsIiRicm93c2VyX3ZlcnNpb24iOiA4OSwiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIiRlbWFpbCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCIkbGFzdF9sb2dpbiI6ICIyMDIxLTAzLTIyVDEwOjE5OjM3In0sIiR0b2tlbiI6ICIxNDgwYjIyNDRmZGQ0ZDgyMTIyN2EyOWUyNjM3ZjkyMiIsIiRkaXN0aW5jdF9pZCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCIkZGV2aWNlX2lkIjogIjE3ODU5NTU2ZmE0MzFmLTA0ZmJjN2M3YWQ5NjhkLTVjM2YxZDRkLTE0NDAwMC0xNzg1OTU1NmZhNTRhNSIsIiR1c2VyX2lkIjogInVkby5waW9udGVrQHdlYi5kZSJ9&ip=1&_=1616408377195 HTTP/1.1" 200 0
[22/Mar/2021 11:19:37] "GET /mixpanel/engage/?data=eyIkc2V0X29uY2UiOiB7IiRlbWFpbCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCIkY3JlYXRlZCI6ICIyMDIxLTAzLTIyVDEwOjE5OjM3In0sIiR0b2tlbiI6ICIxNDgwYjIyNDRmZGQ0ZDgyMTIyN2EyOWUyNjM3ZjkyMiIsIiRkaXN0aW5jdF9pZCI6ICJ1ZG8ucGlvbnRla0B3ZWIuZGUiLCIkZGV2aWNlX2lkIjogIjE3ODU5NTU2ZmE0MzFmLTA0ZmJjN2M3YWQ5NjhkLTVjM2YxZDRkLTE0NDAwMC0xNzg1OTU1NmZhNTRhNSIsIiR1c2VyX2lkIjogInVkby5waW9udGVrQHdlYi5kZSJ9&ip=1&_=1616408377198 HTTP/1.1" 200 0
[22/Mar/2021 11:19:37] "GET /mixpanel/decide/?verbose=1&version=3&lib=web&token=1480b2244fdd4d821227a29e2637f922&distinct_id=udo.piontek%40web.de&ip=1&_=1616408377191 HTTP/1.1" 200 0
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "c:\users\snake\.conda\envs\perceptilabs\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "static_file_server\website_launcher.py", line 60, in static_file_server.website_launcher.launchAndKeepAlive
  File "C:\Users\snake\.conda\envs\perceptilabs\Scripts\perceptilabs.exe\__main__.py", line 7, in <module>
KeyboardInterrupt
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 215, in main
    start(args.verbosity)
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 196, in start
    PortPoller.wait_for_ports()
  File "c:\users\snake\.conda\envs\perceptilabs\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 177, in wait_for_ports
    time.sleep(interval_secs)
KeyboardInterrupt

**Comment by Rolun** [comment]
Hi @WuDou2 ,
It looks like you may have the wrong tensorflow version installed in that environment.
Did you install PerceptiLabs in a fresh new conda environment? And if so, would you mind running "pip list" and post the results here?

All the best,
Robert
