### ISSUE TITLE
Export model issue

### ISSUE THREAD

**Issue by peter197321** [PerceptiLabs/PerceptiLabs#124]
I'm a newbie to your tool and having some problems exporting the model in quantized form, the error looks like this:

> Internal error in asyncio.events:88: Error in create_response Traceback (most recent call last): File "perceptilabs\mainInterface.py", line 261, in perceptilabs.mainInterface.Interface.create_response File "perceptilabs\mainInterface.py", line 481, in perceptilabs.mainInterface.Interface._create_response File "perceptilabs\mainInterface.py", line 607, in perceptilabs.mainInterface.Interface._create_response_export File "perceptilabs\mainInterface.py", line 636, in perceptilabs.mainInterface.Interface._create_response_export_tf1x File "perceptilabs\coreInterface.py", line 351, in perceptilabs.coreInterface.coreLogic.exportNetwork File "perceptilabs\coreInterface.py", line 389, in perceptilabs.coreInterface.coreLogic.exportNetworkV2 File "perceptilabs\coreInterface.py", line 193, in perceptilabs.coreInterface.coreLogic.startCore TypeError: startCore() takes exactly 4 positional arguments (3 given) This will be reported as a bug.

**Comment by Rolun** [comment]
Hi @peter197321 ,
This is a bug with our most recent version, a fix will get pushed up early next week if everything goes as planned.

All the best,
Robert
