### ISSUE TITLE
adding Random_1 datasource error

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#135]
Internal error in asyncio.events:145: Error in create_response (action='getNetworkData')
Traceback (most recent call last):
  File "perceptilabs/mainInterface.py", line 264, in perceptilabs.mainInterface.Interface.create_response
  File "perceptilabs/mainInterface.py", line 361, in perceptilabs.mainInterface.Interface._create_response
  File "perceptilabs/mainInterface.py", line 552, in perceptilabs.mainInterface.Interface._get_network_data
  File "perceptilabs/mainInterface.py", line 83, in perceptilabs.mainInterface.NetworkLoader.load
  File "perceptilabs/graph/spec.py", line 43, in perceptilabs.graph.spec.GraphSpec.from_dict
  File "perceptilabs/graph/spec.py", line 38, in perceptilabs.graph.spec.GraphSpec.from_dict
AttributeError: 'NoneType' object has no attribute 'spec_class'

**Comment by Rolun** [comment]
Hi,

Thank you for letting us know!
Seems that something was missed in the build, will look into adding it and pushing a new version.

All the best,
Robert

**Comment by lievensamijn** [comment]
Thank you for your confirmation.
Best regards,
Lieven

**Comment by Rolun** [comment]
Hi @lievensamijn ,
There is now a new version out which fixes this issue.

All the best,
Robert
