### ISSUE TITLE
cannot import data with csv

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#137]
i've created a very small dataset, just to find out how everything is working. so i start from scratch, add local data and select my csv but i get directly error "ValueError: could not convert string to float: <jpeg file name>
Traceback (most recent call last):
  File "perceptilabs/lwcore/strategies/base.py", line 121, in perceptilabs.lwcore.strategies.base.DataSupervisedStrategy._run_internal
  File "<rendered-code: 1618334917167 [DataData]>", line 69, in sample

  File "<rendered-code: 1618334917167 [DataData]>", line 97, in gen

  File "<rendered-code: 1618334917167 [DataData]>", line 25, in generator_DataData_Local_1_0

  File "/home/develop/.local/lib/python3.6/site-packages/pandas/core/generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "/home/develop/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/home/develop/.local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "/home/develop/.local/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/home/develop/.local/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 997, in astype_nansafe
    return arr.astype(dtype, copy=True)
ValueError: could not convert string to float: 'women/000003.jpg'

csv file:
images,labels
women/000003.jpg,2
women/000002.jpg,2
women/000001.jpg,2
man/000003.jpg,1
man/000002.jpg,1
man/000001.jpg,1

any idea what i'm doing wrong?
Thank you

**Comment by Rolun** [comment]
Hi,

The CSV right now only supports floats inside it.
We will soon have a release which supports exactly that usecase you tried though. Let me know if you are interested in an early build of it and I can send you one.

All the best,
Robeert

**Comment by lievensamijn** [comment]
Hello Robert,
I would like to try the build, if possible
I'm playing on ubuntu 18.04

Thank you in advance!
Very best regards,

Lieven Samijn
