### ISSUE TITLE
Cannot run model with data

### ISSUE THREAD

**Issue by LeviKidder** [PerceptiLabs/PerceptiLabs#146]
Traceback (most recent call last):
  File "perceptilabs\mainInterface.py", line 289, in perceptilabs.mainInterface.Interface.create_response
  File "perceptilabs\mainInterface.py", line 428, in perceptilabs.mainInterface.Interface._create_response
  File "perceptilabs\mainInterface.py", line 602, in perceptilabs.mainInterface.Interface._create_response_model_recommendation
  File "perceptilabs\data\base.py", line 56, in perceptilabs.data.base.DataLoader.from_dict
  File "perceptilabs\data\base.py", line 90, in perceptilabs.data.base.DataLoader.from_features
  File "perceptilabs\data\base.py", line 29, in perceptilabs.data.base.DataLoader.__init__
  File "perceptilabs\data\base.py", line 324, in perceptilabs.data.base.DataLoader._validate_feature_specs
ValueError: Column 'Sac' not in feature specs

[08/May/2021 17:27:07] "OPTIONS /models/72/ HTTP/1.1" 200 0
[08/May/2021 17:27:07] "DELETE /models/72/ HTTP/1.1" 204 0
[08/May/2021 17:27:07] "GET /projects/ HTTP/1.1" 200 264

Always occurs with first column of data, regardless of values or name.

**Comment by Rolun** [comment]
Hi @LeviKidder,

What version of PL are you running on and how does your model look like?

All the best,
Robert

**Comment by sabatale** [comment]
Same here on the latest build - what does "not in feature specs" actually mean?

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sabat/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sabat/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



images | labels
-- | --
carpet/1.jpg | carpet
wood/2.jpg | wood
carpet/3.jpg | carpet
wood/4.jpg | wood
carpet/5.jpg | carpet
carpet/6.jpg | carpet
wood/7.jpg | wood



</body>

</html>


```
2021-06-21 13:10:15,658 - INFO - server.py:293 - Created coreLogic for network ''
2021-06-21 13:10:15,684 - ERROR - server.py:293 - Error in model recommendation
Traceback (most recent call last):
  File "perceptilabs\mainInterface.py", line 601, in perceptilabs.mainInterface.Interface._create_response_model_recommendation
  File "perceptilabs\data\base.py", line 59, in perceptilabs.data.base.DataLoader.from_dict
  File "perceptilabs\data\base.py", line 77, in perceptilabs.data.base.DataLoader.from_features
  File "perceptilabs\data\base.py", line 31, in perceptilabs.data.base.DataLoader.__init__
  File "perceptilabs\data\base.py", line 312, in perceptilabs.data.base.DataLoader._validate_feature_specs
ValueError: Column 'images' not in feature specs
```
