### ISSUE TITLE
Browser Issue 

### ISSUE THREAD

**Issue by asfandiyar007** [PerceptiLabs/PerceptiLabs#147]
Hello Hope you are doing good so today i have freshly made a new anaconda env and installed PL. my OS is Ubuntu 16.04
-------------------------------------------------------------------
**Problems:**
1) no templates when create a new model
 2) In training settings Pressing the **RUN MODEL** & **Customize** Buttons do nothing / not going to next step
-------------------------------------------------------------------
Below are the things i have done
1) tested on both freshly installed Firefox/chrome same result
2) the default mnist_data load perfectly and goes to the next step after training settings
-------------------------------------------------------------------
Browsers console result while pressing the  **RUN MODEL / Customize**  Button
**Firefox:**
![image](https://user-images.githubusercontent.com/12786227/117619172-5c787980-b188-11eb-93ba-31ecce915023.png)
**Chrome:**
0.4b8589c918b4fe421c50.js:316 Loaded claygl, version 1.3.0
0.4b8589c918b4fe421c50.js:316 Loaded echarts, version 4.9.0
0.4b8589c918b4fe421c50.js:282 [KEYCLOAK] Usage of legacy style promise methods such as `.error()` and `.success()` has been deprecated and support will be removed in future versions. Use standard style promise methods such as `.then() and `.catch()` instead.
e.<computed> @ 0.4b8589c918b4fe421c50.js:282
sentry.io/api/1833551/store/?sentry_key=2497f27009b24990b4c0f3feeda4d37d&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
sentry.io/api/1833551/store/?sentry_key=2497f27009b24990b4c0f3feeda4d37d&sentry_version=7:1 Failed to load resource: the server responded with a status of 429 (Too Many Requests)
----------------------------------------------------------------------
Things i tried:
i am a beginner so i don't know alot of stuff but it was showing the error too many attempts  so  i used VPN but still the same result. i think its tracking me using  some token and stuff so probably my next step will be to clear all cookies and caches etc ....(if it works i will let you know ) ...
**Update1:** clearing the cookies & cache didn't worked  also created new account for new token didn't worked as well so maybe some other issue ... the error in browser console is  4**  for API so it means we messed up something.

**Comment by asfandiyar007** [comment]
Thanks for the kind reply Below is the Log i got :
-------------------------------------------------------------------------------
(perceptilabs) rippler@rippler-pc:~$ perceptilabs -v=3
2021-05-11 19:29:29.219455: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 19:29:29.219497: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-11 19:29:31.919836: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 19:29:31.920729: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 19:29:31.920751: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 19:29:31.920777: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (rippler-pc): /proc/driver/nvidia/version does not exist
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
PerceptiLabs: Starting
Performing system checks...

Performing system checks...

2021-05-11 19:29:38.163856: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-11 19:29:38.163957: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
System check identified no issues (0 silenced).
May 11, 2021 - 14:29:38
Django version 3.2, using settings 'static_file_server.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CONTROL-C.
System check identified no issues (0 silenced).
May 11, 2021 - 14:29:39
Django version 3.2, using settings 'fileserver.settings'
Starting development server at http://127.0.0.1:8011/
Quit the server with CONTROL-C.
Performing system checks...

System check identified no issues (0 silenced).
May 11, 2021 - 14:29:39
Django version 3.2, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
2021-05-11 19:29:40.150154: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 19:29:40.150396: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-11 19:29:40.150418: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-11 19:29:40.150453: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (rippler-pc): /proc/driver/nvidia/version does not exist
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
2021-05-11 19:29:42,363 - INFO - <string>:1 - Reporting errors with commit id: 1950b5b6b5a9215316ccfbf0dfd5cb0950545e52
PerceptiLabs is ready...
2021-05-11 19:29:42,427 - INFO - <string>:1 - Trying to listen to: 0.0.0.0 5000
PerceptiLabs: PerceptiLabs Started
PerceptiLabs: PerceptiLabs is running at http://localhost:8080/?token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec
PerceptiLabs: Use Control-C to stop this server and shut down all PerceptiLabs processes.
[11/May/2021 14:29:43] "GET /?token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 493
[11/May/2021 14:29:44] "GET /static/styles/vendors.f99f5b88ec29242cb5db.css HTTP/1.1" 200 68182
[11/May/2021 14:29:44] "GET /static/js/0.4b8589c918b4fe421c50.js HTTP/1.1" 304 0
[11/May/2021 14:29:44] "GET /static/js/app.bbc248426eba8c33e8fd.js HTTP/1.1" 304 0
[11/May/2021 14:29:45] "GET /fileserver_url HTTP/1.1" 200 0
[11/May/2021 14:29:46] "GET /rygg_url HTTP/1.1" 200 0
[11/May/2021 14:29:46] "GET /kernel_url HTTP/1.1" 200 0
[11/May/2021 14:29:47] "GET /is_url_reachable?path=https://keycloak.perceptilabs.com:8443/auth/realms/PerceptiLabs/protocol/openid-connect/3p-cookies/step1.html&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 22
[11/May/2021 14:29:48] "GET /is_url_reachable?path=https://keycloak.perceptilabs.com:8443/auth/realms/PerceptiLabs/protocol/openid-connect/3p-cookies/step1.html&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 22
[11/May/2021 14:30:01] "GET /?token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 493
[11/May/2021 14:30:01] "GET /fileserver_url HTTP/1.1" 200 0
[11/May/2021 14:30:01] "GET /rygg_url HTTP/1.1" 200 0
[11/May/2021 14:30:01] "GET /kernel_url HTTP/1.1" 200 0
[11/May/2021 14:30:02] "GET /is_url_reachable?path=https://keycloak.perceptilabs.com:8443/auth/realms/PerceptiLabs/protocol/openid-connect/3p-cookies/step1.html&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 22
[11/May/2021 14:30:04] "GET /is_url_reachable?path=https://keycloak.perceptilabs.com:8443/auth/realms/PerceptiLabs/protocol/openid-connect/3p-cookies/step1.html&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 22
[11/May/2021 14:30:05] "GET /static/img/tutorial-background.ac2e517.png HTTP/1.1" 200 186377
[11/May/2021 14:30:05] "GET /static/fonts/nunito-sans-v5-latin-600.b56c7e1.woff2 HTTP/1.1" 200 16900
[11/May/2021 14:30:05] "GET /static/fonts/nunito-sans-v5-latin-700.d0b6d0f.woff2 HTTP/1.1" 304 0
[11/May/2021 14:30:05] "GET /static/fonts/nunito-sans-v5-latin-regular.9c6a1ff.woff2 HTTP/1.1" 304 0
[11/May/2021 14:30:05] "GET /rygg_url HTTP/1.1" 200 0
[11/May/2021 14:30:05] "GET /version?token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 21
[11/May/2021 14:30:05] "GET /static/fonts/icomoon.1b9c004.woff HTTP/1.1" 200 39096
[11/May/2021 14:30:05] "GET /projects/ HTTP/1.1" 200 261
[11/May/2021 14:30:05] "GET /models/85/ HTTP/1.1" 200 230
2021-05-11 19:30:05,465 - INFO - server.py:293 - Created coreLogic for network 'None'
[11/May/2021 14:30:05] "GET /json_models?path=/home/rippler/Documents/Perceptilabs/Default/Asfand/model.json&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 7756
[11/May/2021 14:30:05] "GET /json_models?path=/home/rippler/Documents/Perceptilabs/Default/Asfand/model.json&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 7756
[11/May/2021 14:30:05] "HEAD /files?path=/home/rippler/Documents/Perceptilabs/Default/Asfand/model.json&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 74
[11/May/2021 14:30:05] "HEAD /directories?path=/home/rippler/Documents/Perceptilabs/Default/Asfand&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 63
[11/May/2021 14:30:05] "POST /json_models?path=/home/rippler/Documents/Perceptilabs/Default/Asfand&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 74
[11/May/2021 14:30:05] "HEAD /directories?path=/home/rippler/Documents/Perceptilabs/Default/Asfand&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 63
2021-05-11 19:30:05,675 - INFO - server.py:293 - Created coreLogic for network ''
2021-05-11 19:30:05,675 - INFO - server.py:293 - User has been set to asfandiyar007@gmail.com
[11/May/2021 14:30:05] "POST /mixpanel/track/?ip=1&_=1620743405561 HTTP/1.1" 200 0
[11/May/2021 14:30:06] "GET /mixpanel/decide/?verbose=1&version=1&lib=web&token=1480b2244fdd4d821227a29e2637f922&ip=1&_=1620743405548 HTTP/1.1" 200 0
2021-05-11 19:30:07,235 - INFO - server.py:293 - Created coreLogic for network '85'
[11/May/2021 14:30:07] "GET /app/updates_available/ HTTP/1.1" 200 22
[11/May/2021 14:30:10] "POST /mixpanel/engage/?ip=1&_=1620743410318 HTTP/1.1" 200 0
[11/May/2021 14:30:10] "POST /mixpanel/engage/?ip=1&_=1620743410321 HTTP/1.1" 200 0
[11/May/2021 14:30:13] "GET /mixpanel/decide/?verbose=1&version=3&lib=web&token=1480b2244fdd4d821227a29e2637f922&distinct_id=asfandiyar007%40gmail.com&ip=1&_=1620743410313 HTTP/1.1" 200 0
[11/May/2021 14:30:18] "GET /directories/get_folder_content?path=/home/rippler/Desktop&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 335
[11/May/2021 14:30:18] "GET /static/img/file-picker/folder.svg HTTP/1.1" 200 307
[11/May/2021 14:30:18] "GET /static/img/file-picker/home.svg HTTP/1.1" 200 664
[11/May/2021 14:30:18] "GET /static/img/file-picker/file.svg HTTP/1.1" 200 304
('/home/rippler/Desktop/IRIS.csv', 4)
[11/May/2021 14:30:21] "GET /files/get_file_content?path=/home/rippler/Desktop/IRIS.csv&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 179
[11/May/2021 14:30:21] "GET /static/fonts/roboto-regular-webfont.736b705.woff2 HTTP/1.1" 200 20000
[11/May/2021 14:30:21] "GET /directories/resolved_dir?path=/home/rippler/Documents/Perceptilabs/Default&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 56
[11/May/2021 14:30:21] "GET /directories/get_folder_content?path=/home/rippler/Documents/Perceptilabs/Default&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 200 118
[11/May/2021 14:30:42] "GET /models/85/ HTTP/1.1" 200 230
[11/May/2021 14:30:42] "HEAD /directories?path=/home/rippler/Documents/Perceptilabs/Default/lol&token=hza9Lq2vJPtym7LNk6mXMAKJfcRU7N-AQLkaXppPnec HTTP/1.1" 204 34
[11/May/2021 14:30:42] "OPTIONS /models/ HTTP/1.1" 200 0
[11/May/2021 14:30:42] "POST /models/ HTTP/1.1" 201 225
2021-05-11 19:30:42.371449: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-05-11 19:30:42.372329: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-05-11 19:30:42,832 - ERROR - server.py:293 - Error in create_response (action='getModelRecommendation') (issue origin: asyncio.events:88)
Traceback (most recent call last):
  File "perceptilabs/mainInterface.py", line 289, in perceptilabs.mainInterface.Interface.create_response
  File "perceptilabs/mainInterface.py", line 428, in perceptilabs.mainInterface.Interface._create_response
  File "perceptilabs/mainInterface.py", line 605, in perceptilabs.mainInterface.Interface._create_response_model_recommendation
  File "perceptilabs/modelrecommender/base.py", line 46, in perceptilabs.modelrecommender.base.ModelRecommender.get_graph
  File "perceptilabs/modelrecommender/base.py", line 61, in perceptilabs.modelrecommender.base.ModelRecommender._connect_encoders_and_decoders
NotImplementedError: A maximum of two input encoders are supported right now

[11/May/2021 14:30:42] "OPTIONS /models/106/ HTTP/1.1" 200 0
[11/May/2021 14:30:42] "DELETE /models/106/ HTTP/1.1" 204 0
[11/May/2021 14:30:42] "GET /projects/ HTTP/1.1" 200 261

**Comment by Rolun** [comment]
Hi @asfandiyar007 ,
Thanks for the logs!

Looking at this error:
```
Traceback (most recent call last):
File "perceptilabs/mainInterface.py", line 289, in perceptilabs.mainInterface.Interface.create_response
File "perceptilabs/mainInterface.py", line 428, in perceptilabs.mainInterface.Interface._create_response
File "perceptilabs/mainInterface.py", line 605, in perceptilabs.mainInterface.Interface._create_response_model_recommendation
File "perceptilabs/modelrecommender/base.py", line 46, in perceptilabs.modelrecommender.base.ModelRecommender.get_graph
File "perceptilabs/modelrecommender/base.py", line 61, in perceptilabs.modelrecommender.base.ModelRecommender._connect_encoders_and_decoders
NotImplementedError: A maximum of two input encoders are supported right now
```
It seems like something in the data defining part went wrong.
Did you say that this error happened when you tried with the mnist data, or your custom data?

If you send a screenshot of how the data is defined in the tool I can take a look at what might have gone wrong :)
