### ISSUE TITLE
Waiting for services to listen on these ports: frontend on port 8080

### ISSUE THREAD

**Issue by adras** [PerceptiLabs/PerceptiLabs#151]
Seems to be an endless loop after the latest update :(

(myenv) C:\Users\andre>perceptilabs
INFORMATION: Es konnten keine Dateien mit dem angegebenen
Muster gefunden werden.
PerceptiLabs: Your environment does not have git installed, so interactions with GitHub will not be available
2021-06-16 23:11:53.462854: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-16 23:11:53.463044: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-06-16 23:11:55.487508: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-16 23:11:55.488595: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-16 23:11:56.194068: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: NVIDIA GeForce GPU computeCapability: 5.0
coreClock: 0.993GHz coreCount: 3 deviceMemorySize: 1.00GiB deviceMemoryBandwidth: 37.33GiB/s
2021-06-16 23:11:56.195170: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-06-16 23:11:56.196027: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublas64_11.dll'; dlerror: cublas64_11.dll not found
2021-06-16 23:11:56.196855: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cublasLt64_11.dll'; dlerror: cublasLt64_11.dll not found
2021-06-16 23:11:56.197681: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2021-06-16 23:11:56.198529: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2021-06-16 23:11:56.199358: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2021-06-16 23:11:56.200219: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cusparse64_11.dll'; dlerror: cusparse64_11.dll not found
2021-06-16 23:11:56.201341: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudnn64_8.dll'; dlerror: cudnn64_8.dll not found
2021-06-16 23:11:56.201495: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
PerceptiLabs: Starting
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
Traceback (most recent call last):
  File "c:\users\andre\anaconda\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\andre\anaconda\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\andre\Anaconda\envs\myenv\Scripts\perceptilabs.exe\__main__.py", line 7, in <module>
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 229, in main
    start(args.verbosity)
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 210, in start
    PortPoller.wait_for_ports()
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 181, in wait_for_ports
    time.sleep(interval_secs)
KeyboardInterrupt
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\sentry_sdk\worker.py", line 108, in flush
    self._wait_flush(timeout, callback)
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\sentry_sdk\worker.py", line 119, in _wait_flush
    self._timed_queue_join(timeout - initial_timeout)
  File "c:\users\andre\anaconda\envs\myenv\lib\site-packages\sentry_sdk\worker.py", line 65, in _timed_queue_join
    all_tasks_done.wait(timeout=delay)
  File "c:\users\andre\anaconda\envs\myenv\lib\threading.py", line 300, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt

(myenv) C:\Users\andre>time
Aktuelle Zeit: 23:21:16,55

**Comment by haidermri** [comment]
I am having a similar issue. Installed on Win 10 running minconda to create separate perceptilab environment
(percepti) C:\Users\mahai>perceptilabs -v=3
2021-06-17 10:07:59.426988: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-17 10:08:01.999953: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-17 10:08:02.000925: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-17 10:08:02.022620: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-17 10:08:02.022924: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-17 10:08:02.030919: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-17 10:08:02.031059: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-17 10:08:02.036109: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-17 10:08:02.037561: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-17 10:08:02.046141: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-17 10:08:02.049665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-17 10:08:02.050808: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-17 10:08:02.051556: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
PerceptiLabs: Starting
2021-06-17 10:08:03.950305: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
Performing system checks...

Performing system checks...

Traceback (most recent call last):
  File "c:\users\mahai\miniconda3\envs\percepti\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\__main__.py", line 9, in <module>
    management.execute_from_command_line()
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\commands\runserver.py", line 61, in execute
    super().execute(*args, **options)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\commands\runserver.py", line 96, in handle
    self.run(**options)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\commands\runserver.py", line 105, in run
    self.inner_run(None, **options)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\management\base.py", line 423, in check
    databases=databases,
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\checks\registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\checks\urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\core\checks\urls.py", line 23, in check_resolver
    return check_method()
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\urls\resolvers.py", line 412, in check
    for pattern in self.url_patterns:
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\urls\resolvers.py", line 598, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\site-packages\django\urls\resolvers.py", line 591, in urlconf_module
    return import_module(self.urlconf_name)
  File "c:\users\mahai\miniconda3\envs\percepti\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 929, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "static_file_server\urls.py", line 9, in init static_file_server.urls
  File "static_file_server\views.py", line 10, in init static_file_server.views
ModuleNotFoundError: No module named 'websocket'
Performing system checks...

System check identified no issues (0 silenced).
June 17, 2021 - 10:08:04
Django version 3.2, using settings 'fileserver.settings'
Starting development server at http://127.0.0.1:8011/
Quit the server with CTRL-BREAK.
System check identified no issues (0 silenced).
June 17, 2021 - 10:08:05
Django version 3.2, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
2021-06-17 10:08:06.664488: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-06-17 10:08:06.665277: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-06-17 10:08:06.691198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 Ti computeCapability: 6.1
coreClock: 1.582GHz coreCount: 28 deviceMemorySize: 11.00GiB deviceMemoryBandwidth: 451.17GiB/s
2021-06-17 10:08:06.691359: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-06-17 10:08:06.697556: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-06-17 10:08:06.697683: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-06-17 10:08:06.701043: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-06-17 10:08:06.702244: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-06-17 10:08:06.707778: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-06-17 10:08:06.710018: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-06-17 10:08:06.711572: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-06-17 10:08:06.711849: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-06-17 10:08:08,357 - INFO - <string>:1 - Reporting errors with commit id: 8930db3f0df534d0410f58040bee719dfd1e1f92
PerceptiLabs is ready...
2021-06-17 10:08:08,400 - INFO - <string>:1 - Trying to listen to: 0.0.0.0 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    frontend on port 8080

**Comment by haidermri** [comment]
When I go back to 0.11.8 everything works

**Comment by Vortex93** [comment]
> When I go back to 0.11.8 everything works

How do you downgrade the version?
Whenever I do _pip install perceptilabs==0.11.8_

It throws this error:
`
ERROR: Could not find a version that satisfies the requirement perceptilabs==0.11.8 (from versions: 0.12.9)
ERROR: No matching distribution found for perceptilabs==0.11.8
`

**Comment by Vortex93** [comment]
So I believe I managed to solve this problem. 
If you run perceptilabs in verbose by running _perceptilabs -v 2_ check if it throws an import error somewhere in the output.

In my case I got _no module named websocket_, so I did _pip install websocket-client_ and this solved my problem.

**Comment by sabatale** [comment]
@Vortex93 Thanks! You solved my issue!
