### ISSUE TITLE
Cant run percptilabs using conda?

### ISSUE THREAD

**Issue by nikkisingh111333** [PerceptiLabs/PerceptiLabs#162]
i m folllowing perceptilabs docs instaling is doing fin but when i try to run perceptilabs it throws me this error:
`**(myenv) C:\Users\ACER>perceptilabs**

`Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\pkg_resources\__init__.py", line 344, in get_provider
    module = sys.modules[moduleOrReq]
KeyError: 'perceptilabs'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\ACER\anaconda3\envs\myenv\Scripts\perceptilabs.exe\__main__.py", line 4, in <module>
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\perceptilabs_runner\perceptilabs_runner.py", line 76, in <module>
    TUTORIAL_DATA_PATH = pkg_resources.resource_filename('perceptilabs', 'tutorial_data')
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\pkg_resources\__init__.py", line 1130, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\pkg_resources\__init__.py", line 346, in get_provider
    __import__(moduleOrReq)
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\perceptilabs\__init__.py", line 1, in <module>
    from perceptilabs.mainServer import main
  File "perceptilabs\mainServer.py", line 9, in init perceptilabs.mainServer
  File "perceptilabs\utils.py", line 23, in init perceptilabs.utils
  File "C:\Users\ACER\anaconda3\envs\myenv\lib\site-packages\pandas\__init__.py", line 16, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
dateutil: No module named 'dateutil'
Sentry is attempting to send 2 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit`

Why this is happening ?
please show me the correct way of installing PerceptiLabs
please help me solving this issue

**Comment by nikkisingh111333** [comment]
hello no response?
