### ISSUE TITLE
Create Model: Error msg "Kernel offline"

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#44]
Hi,, on clicking to create model..A pop messaging that "Kernel is offline".. Kindly help

**Comment by Rolun** [comment]
Hi,
If you run the tool as `perceptilabs -v=3` you will get a full log of everything that happens. Would you mind posting that log here so I can take a look?

All the best,
Robert

**Comment by TheGritz** [comment]
im having the same problem.... heres my log though,


C:\Users\Zaeem>perceptilabs -v=3
INFO: Could not find files for the given pattern(s).
PerceptiLabs: Your environment does not have git installed, so interactions with GitHub will not be available
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
PerceptiLabs: Starting
Traceback (most recent call last):
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\platform\self_check.py", line 47, in preload_check
    ctypes.WinDLL(build_info.msvcp_dll_name)
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\perceptilabs\__init__.py", line 1, in <module>
    from perceptilabs.mainServer import main
  File "perceptilabs\mainServer.py", line 10, in init perceptilabs.mainServer
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "c:\users\zaeem\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\platform\self_check.py", line 55, in preload_check
    % build_info.msvcp_dll_name)
ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. You may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 from this URL: https://www.microsoft.com/en-us/download/details.aspx?id=53587
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
December 20, 2020 - 13:35:40
Django version 3.1.4, using settings 'static_file_server.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CTRL-BREAK.
System check identified no issues (0 silenced).
December 20, 2020 - 13:35:40
Django version 3.1.4, using settings 'fileserver.settings'
Starting development server at http://127.0.0.1:8011/
Quit the server with CTRL-BREAK.
Performing system checks...

[20/Dec/2020 13:35:43] "GET /?token=jzB2a65eMEMMsuSTbLI5Ei1j2FvPexLEX5EpqMTXKZY HTTP/1.1" 200 493
[20/Dec/2020 13:35:43] "GET /kernel_url HTTP/1.1" 200 0
[20/Dec/2020 13:35:43] "GET /fileserver_url HTTP/1.1" 200 0
System check identified no issues (0 silenced).
December 20, 2020 - 13:35:43
Django version 3.1.4, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[20/Dec/2020 13:35:44] "GET /rygg_url HTTP/1.1" 200 0
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
[20/Dec/2020 13:37:11] "GET /?token=jzB2a65eMEMMsuSTbLI5Ei1j2FvPexLEX5EpqMTXKZY HTTP/1.1" 200 493
[20/Dec/2020 13:37:11] "GET /kernel_url HTTP/1.1" 200 0
[20/Dec/2020 13:37:11] "GET /fileserver_url HTTP/1.1" 200 0
[20/Dec/2020 13:37:11] "GET /rygg_url HTTP/1.1" 200 0
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
[20/Dec/2020 13:37:13] "GET /rygg_url HTTP/1.1" 200 0
[20/Dec/2020 13:37:14] "GET /static/img/tutorial-background.ac2e517.png HTTP/1.1" 304 0
[20/Dec/2020 13:37:14] "GET /static/fonts/nunito-sans-v5-latin-600.b56c7e1.woff2 HTTP/1.1" 304 0
[20/Dec/2020 13:37:14] "GET /static/fonts/nunito-sans-v5-latin-regular.9c6a1ff.woff2 HTTP/1.1" 304 0
[20/Dec/2020 13:37:14] "GET /static/fonts/icomoon.9d6c449.woff HTTP/1.1" 304 0
[20/Dec/2020 13:37:14] "GET /static/fonts/nunito-sans-v5-latin-700.d0b6d0f.woff2 HTTP/1.1" 304 0
[20/Dec/2020 13:37:14] "GET /version?token=jzB2a65eMEMMsuSTbLI5Ei1j2FvPexLEX5EpqMTXKZY HTTP/1.1" 200 21
[20/Dec/2020 13:37:15] "GET /projects/ HTTP/1.1" 200 265
[20/Dec/2020 13:37:15] "GET /mixpanel/decide/?verbose=1&version=1&lib=web&token=1480b2244fdd4d821227a29e2637f922&ip=1&_=1608453434363 HTTP/1.1" 200 0
[20/Dec/2020 13:37:16] "GET /app/updates_available/ HTTP/1.1" 200 22
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
[20/Dec/2020 13:37:19] "GET /mixpanel/engage/?data=eyIkc2V0IjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkNocm9tZSIsIiRicm93c2VyX3ZlcnNpb24iOiA4NywiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIiRlbWFpbCI6ICJ6YWVlbW1vaHNpbjIwMDdAZ21haWwuY29tIiwiJGxhc3RfbG9naW4iOiAiMjAyMC0xMi0yMFQwODozNzoxOCJ9LCIkdG9rZW4iOiAiMTQ4MGIyMjQ0ZmRkNGQ4MjEyMjdhMjllMjYzN2Y5MjIiLCIkZGlzdGluY3RfaWQiOiAiemFlZW1tb2hzaW4yMDA3QGdtYWlsLmNvbSIsIiRkZXZpY2VfaWQiOiAiMTc2N2QzZDM5ZWUxYjMtMGVhMTZhYTZmODZkMjMtYzc5MTAzOS0xMDAyMDAtMTc2N2QzZDM5ZWYxYmIiLCIkdXNlcl9pZCI6ICJ6YWVlbW1vaHNpbjIwMDdAZ21haWwuY29tIn0%3D&ip=1&_=1608453438848 HTTP/1.1" 200 0
[20/Dec/2020 13:37:19] "GET /mixpanel/engage/?data=eyIkc2V0X29uY2UiOiB7IiRlbWFpbCI6ICJ6YWVlbW1vaHNpbjIwMDdAZ21haWwuY29tIiwiJGNyZWF0ZWQiOiAiMjAyMC0xMi0yMFQwODozNzoxOCJ9LCIkdG9rZW4iOiAiMTQ4MGIyMjQ0ZmRkNGQ4MjEyMjdhMjllMjYzN2Y5MjIiLCIkZGlzdGluY3RfaWQiOiAiemFlZW1tb2hzaW4yMDA3QGdtYWlsLmNvbSIsIiRkZXZpY2VfaWQiOiAiMTc2N2QzZDM5ZWUxYjMtMGVhMTZhYTZmODZkMjMtYzc5MTAzOS0xMDAyMDAtMTc2N2QzZDM5ZWYxYmIiLCIkdXNlcl9pZCI6ICJ6YWVlbW1vaHNpbjIwMDdAZ21haWwuY29tIn0%3D&ip=1&_=1608453438851 HTTP/1.1" 200 0
[20/Dec/2020 13:37:19] "GET /mixpanel/decide/?verbose=1&version=3&lib=web&token=1480b2244fdd4d821227a29e2637f922&distinct_id=zaeemmohsin2007%40gmail.com&ip=1&_=1608453438844 HTTP/1.1" 200 0
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000
PerceptiLabs: Waiting for services to listen on these ports:
PerceptiLabs:    kernel on port 5000

**Comment by Rolun** [comment]
Hey,

From the log, it looks like TensorFlow was not installed properly. Especially this part of the log stands out:
`ImportError: Could not find 'msvcp140.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. You may install this DLL by downloading Visual C++ 2015 Redistributable Update 3 from this URL: https://www.microsoft.com/en-us/download/details.aspx?id=53587`

Have you had TensorFlow installed on your machine before?
