### ISSUE TITLE
Error:waiting for services to listen on these ports, kernel on port 5000

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#61]
I do not know what to do, it repeatedly says 'waiting for services to listen to these ports, kernel on port 5000' in cmd. And when it opens perceptilabs in browser, then it just says that kernel is offline for whatever i do

**Comment by Rolun** [comment]
Hi,
Sorry to hear you are having this problem.

Would you mind running perceptilabs as "perceptilabs -v=3" and printing the log here? Then we can take a look at what may have gone wrong.

Best regards,
Robert

**Comment by smoothjazzuser** [comment]
I think it is related to a kernel crash. I got this problem as well. It went away when I used scipy==1.4.1 instead of the latest one, which apparently is buggy and stopped the kernel from running.

**Comment by timothywalter** [comment]
> 
> 
> Hi,
> Sorry to hear you are having this problem.
> 
> Would you mind running perceptilabs as "perceptilabs -v=3" and printing the log here? Then we can take a look at what may have gone wrong.
> 
> Best regards,
> Robert

When I had this problem and ran with -v=3 I found out I got a permission error writing the kernel.log file. Running the command prompt in an Administrator role, before executing the `perceptilabs` commandfixed the problem.

**Comment by timothywalter** [comment]
Additionally after not heading any advice and choosing to **not virtualise python or tensorflow** you can cause a conflicting installation of tensorflow. For me this also caused the kernel to not launch and give this error.

Relevant part of `-v=3` log:
```
System check identified no issues (0 silenced).
January 16, 2021 - 21:57:54
Django version 3.1.5, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\program files\python37\lib\site-packages\perceptilabs\__init__.py", line 1, in <module>
    from perceptilabs.mainServer import main
  File "perceptilabs\mainServer.py", line 29, in init perceptilabs.mainServer
AttributeError: module 'tensorflow' has no attribute 'disable_v2_behavior'
Sentry is attempting to send 0 pending error messages
Waiting up to 2 seconds
Press Ctrl-Break to quit
```

To fix this I used the following commands to uninstall tensorflow and perceptilabs:
`pip uninstall tensorflow`
`pip uninstall perceptilabs`
`pip install perceptilabs`

In the future follow the advice and install tensorflow, tsjs etc through a virtualized environment such as conda or pyenv

**Comment by stefkwan-h8** [comment]
![image](https://github.com/PerceptiLabs/PerceptiLabs/assets/82027557/5c8c86f4-1c0f-4bad-b658-8d820132b861)
I have the same issue, tried creating conda environment for python 3.8, uninstall tensorflow, uninstall perceptilabs, install perceptilabs, still persists.
