### ISSUE TITLE
MacOS installation exits with error: Possible Azure deprecated?

### ISSUE THREAD

**Issue by cunundrummer** [PerceptiLabs/PerceptiLabs#65]
Azure issue perhaps? I don't use any MS services if that is important.  Also, python version is 3.7.

$ pip3 install perceptilabs
All requirements...
.
.
.
Requirement already satisfied: protobuf>=3.6.1 in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (from tensorflow==1.13.1->perceptilabs) (3.12.0)
Collecting azure-storage>=0.36.0
  Using cached azure-storage-0.37.0.zip (4.3 kB)
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-201d2rqg/azure-storage_d27b2177264a436487b1474e2ed105a2/setup.py'"'"'; __file__='"'"'/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-201d2rqg/azure-storage_d27b2177264a436487b1474e2ed105a2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-pip-egg-info-i5cjovts
         cwd: /private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-201d2rqg/azure-storage_d27b2177264a436487b1474e2ed105a2/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-201d2rqg/azure-storage_d27b2177264a436487b1474e2ed105a2/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by cunundrummer** [comment]
Found [this](https://github.com/Azure/azure-sdk-for-python/issues/11413) (if it helps)

**Comment by kollmats** [comment]
Hi @cunundrummer,

thanks for bringing this issue to our attention. I'll look into this asap and get back to you once I know more :)

**Comment by kollmats** [comment]
Hi again @cunundrummer,

we have now rolled out a new version with a potential fix. If you go ahead and reinstall PerceptiLabs it should work as expected.

Thanks again for letting us know about this!

**Comment by cunundrummer** [comment]
Still have the same issue. 

> RuntimeError:
> 
>     Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
>     Please install the service specific packages prefixed by `azure` needed for your application.

Is azure necessary? I don't see it on the [requirements](https://www.perceptilabs.com/docs/requirements) page.  Maybe I can resolve this issue with MS's suggestion of installing one of their packages? -
    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

But I am not sure it'll still work nor do I know which to install - might require backend update?

**Comment by kollmats** [comment]
Yes, a fresh install of perceptilabs should give you the correct azure version. What does pip list say?

**Comment by cunundrummer** [comment]
I'm trying now with ` pipenv install perceptilabs`.

```
.
.
.
Collecting azure-storage>=0.36.0
  Using cached azure-storage-0.37.0.zip (4.3 kB)


    ERROR: Command errored out with exit status 1:
     command: /Users/xxx/.local/share/virtualenvs/PythonProjects-PL-9V0ST/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-lurtq187/azure-storage/setup.py'"'"'; __file__='"'"'/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-lurtq187/azure-storage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-pip-egg-info-dfb5_3j2
         cwd: /private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-lurtq187/azure-storage/
    Complete output (19 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5j/rqjn1f3926b339w902c58dc40000gn/T/pip-install-lurtq187/azure-storage/setup.py", line 55, in <module>
        raise RuntimeError(message)
    RuntimeError:

    Starting with v0.37.0, the 'azure-storage' meta-package is deprecated and cannot be installed anymore.
    Please install the service specific packages prefixed by `azure` needed for your application.

    The complete list of available packages can be found at:
    https://aka.ms/azsdk/python/all

    Here's a non-exhaustive list of common packages:

    - [azure-storage-blob](https://pypi.org/project/azure-storage-blob) : Blob storage client
    - [azure-storage-file-share](https://pypi.org/project/azure-storage-file-share) : Storage file share client
    - [azure-storage-file-datalake](https://pypi.org/project/azure-storage-file-datalake) : ADLS Gen2 client
    - [azure-storage-queue](https://pypi.org/project/azure-storage-queue): Queue storage client

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

This is likely caused by a bug in perceptilabs. Report this to its maintainers.
✘ Installation Failed
```

**Comment by Social-Enigma** [comment]
Looks like it's trying to use a version of azure storage that was meant to deprecate it. Using

pip install azure-storage==0.36.0

before trying to install perceptilabs seems to fix the issue for me. Perhaps restricting the azure storage version to only v0.36.0 will fix the issue?

**Comment by cunundrummer** [comment]
Thanks @Social-Enigma, it worked!  I cannot believe I didn't think of that. Facepalm.
