### ISSUE TITLE
No preview shown

### ISSUE THREAD

**Issue by AnonymousPerceptiLabs** [PerceptiLabs/PerceptiLabs#73]
On all my components no preview is shown.

**Comment by Rolun** [comment]
Hi,
Thank you for letting us know!

2 followup questions if you don't mind:
1. Can you post a screenshot of how it looks like, preferably with the browser console open (press F12)?
2. When you run it, can you run it as "perceptilabs -v=3" and copy paste the printout to here? 

All the best,
Robert

**Comment by Nakrum** [comment]
Hey,
sure no problem, here the "perceptilabs -v=3" printout:

<details>
<summary>printout</summary>

```
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, sessions
Running migrations:
  No migrations to apply.
PerceptiLabs: Starting
2021-01-25 16:03:00.523316: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2021-01-25 16:03:00.527563: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Performing system checks...

Performing system checks...

System check identified no issues (0 silenced).
January 25, 2021 - 16:03:00
Django version 3.1.5, using settings 'static_file_server.settings'
Starting development server at http://127.0.0.1:8080/
Quit the server with CTRL-BREAK.
System check identified no issues (0 silenced).
January 25, 2021 - 16:03:01
Django version 3.1.5, using settings 'fileserver.settings'
Starting development server at http://127.0.0.1:8011/
Quit the server with CTRL-BREAK.
Performing system checks...

System check identified no issues (0 silenced).
January 25, 2021 - 16:03:01
Django version 3.1.5, using settings 'rygg.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\tensorflow_core\python\compat\v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[25/Jan/2021 16:03:02] "GET /?token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 493
[25/Jan/2021 16:03:02] "GET /static/styles/vendors.512a294ee5017c3b65db.css HTTP/1.1" 200 1668
[25/Jan/2021 16:03:02] "GET /static/js/1.b98a3dee54f2bf18fefe.js HTTP/1.1" 304 0
[25/Jan/2021 16:03:02] "GET /static/js/app.b35ce83014b8607a06ae.js HTTP/1.1" 304 0
[25/Jan/2021 16:03:02] "GET /fileserver_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:02] "GET /kernel_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:03] "GET /rygg_url HTTP/1.1" 200 0
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53920)
Traceback (most recent call last):
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "h:\anaconda\envs\pl\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "h:\anaconda\envs\pl\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "h:\anaconda\envs\pl\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
----------------------------------------
2021-01-25 16:03:03,233 - INFO - <string>:1 - Reporting errors with commit id: 8009450650e00e4a8ab5a7b6d40e7df044a3affc
PerceptiLabs is ready...
2021-01-25 16:03:03,263 - INFO - <string>:1 - Trying to listen to: 0.0.0.0 5000
2021-01-25 16:03:03,509 - INFO - server.py:191 - Created coreLogic for network 'None'
[25/Jan/2021 16:03:03] "GET /?token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 493
[25/Jan/2021 16:03:04] "GET /fileserver_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:04] "GET /kernel_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:04] "GET /rygg_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:04] "GET /rygg_url HTTP/1.1" 200 0
[25/Jan/2021 16:03:04] "GET /version?token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 21
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 53940)
Traceback (most recent call last):
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "h:\anaconda\envs\pl\lib\socketserver.py", line 720, in __init__
    self.handle()
  File "h:\anaconda\envs\pl\lib\site-packages\django\core\servers\basehttp.py", line 174, in handle
    self.handle_one_request()
  File "h:\anaconda\envs\pl\lib\site-packages\django\core\servers\basehttp.py", line 182, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "h:\anaconda\envs\pl\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
ConnectionAbortedError: [WinError 10053] Eine bestehende Verbindung wurde softwaregesteuert
durch den Hostcomputer abgebrochen
----------------------------------------
[25/Jan/2021 16:03:04] "HEAD /directories?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Tut%20Test&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 68
[25/Jan/2021 16:03:04] "HEAD /directories?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Model%201&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 67
PerceptiLabs: PerceptiLabs Started
PerceptiLabs: PerceptiLabs is running at http://localhost:8080/?token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI
PerceptiLabs: Use Control-C to stop this server and shut down all PerceptiLabs processes.
[25/Jan/2021 16:03:05] "GET /projects/ HTTP/1.1" 200 264
[25/Jan/2021 16:03:05] "GET /models/1/ HTTP/1.1" 200 235
[25/Jan/2021 16:03:05] "GET /models/2/ HTTP/1.1" 200 233
[25/Jan/2021 16:03:05] "GET /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Tut%20Test/model.json&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 9629
[25/Jan/2021 16:03:05] "GET /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Tut%20Test/model.json&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 9629
[25/Jan/2021 16:03:05] "GET /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Model%201/model.json&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 15973
[25/Jan/2021 16:03:05] "GET /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Model%201/model.json&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 15973
[25/Jan/2021 16:03:05] "GET /mixpanel/track/?data=eyJldmVudCI6ICJtcF9wYWdlX3ZpZXciLCJwcm9wZXJ0aWVzIjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkY3VycmVudF91cmwiOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgwLz90b2tlbj1XMHNTUHpYMkhkTEdRbnRYbUhJcWgzc1dJMTltcVc2TzNjcGhjb3B5RWRJIiwiJGJyb3dzZXJfdmVyc2lvbiI6IDg0LCIkc2NyZWVuX2hlaWdodCI6IDEwODAsIiRzY3JlZW5fd2lkdGgiOiAxOTIwLCJtcF9saWIiOiAid2ViIiwiJGxpYl92ZXJzaW9uIjogIjIuMjkuMSIsInRpbWUiOiAxNjExNTg2OTg0LjkxNywiZGlzdGluY3RfaWQiOiAiYWxiYW5hMTcwOEBob3RtYWlsLmRlIiwiJGRldmljZV9pZCI6ICIxNzcxNWFjZTRkYTNhNy0wYjJkZGMwNTMzYzM4MTgtNGMzZjIwN2UtMWZhNDAwLTE3NzE1YWNlNGRiMjEzIiwiJGluaXRpYWxfcmVmZXJyZXIiOiAiJGRpcmVjdCIsIiRpbml0aWFsX3JlZmVycmluZ19kb21haW4iOiAiJGRpcmVjdCIsIiR1c2VyX2lkIjogImFsYmFuYTE3MDhAaG90bWFpbC5kZSIsIm1wX3BhZ2UiOiAiaHR0cDovL2xvY2FsaG9zdDo4MDgwLz90b2tlbj1XMHNTUHpYMkhkTEdRbnRYbUhJcWgzc1dJMTltcVc2TzNjcGhjb3B5RWRJIiwibXBfYnJvd3NlciI6ICJGaXJlZm94IiwibXBfcGxhdGZvcm0iOiAiV2luZG93cyIsInRva2VuIjogIjE0ODBiMjI0NGZkZDRkODIxMjI3YTI5ZTI2MzdmOTIyIn19&ip=1&_=1611586984918 HTTP/1.1" 200 0
[25/Jan/2021 16:03:05] "GET /mixpanel/decide/?verbose=1&version=1&lib=web&token=1480b2244fdd4d821227a29e2637f922&ip=1&_=1611586984915 HTTP/1.1" 200 0
[25/Jan/2021 16:03:05] "GET /mixpanel/track/?data=eyJldmVudCI6ICIkb3B0X2luIiwicHJvcGVydGllcyI6IHsiJG9zIjogIldpbmRvd3MiLCIkYnJvd3NlciI6ICJGaXJlZm94IiwiJGN1cnJlbnRfdXJsIjogImh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC8%2FdG9rZW49VzBzU1B6WDJIZExHUW50WG1ISXFoM3NXSTE5bXFXNk8zY3BoY29weUVkSSIsIiRicm93c2VyX3ZlcnNpb24iOiA4NCwiJHNjcmVlbl9oZWlnaHQiOiAxMDgwLCIkc2NyZWVuX3dpZHRoIjogMTkyMCwibXBfbGliIjogIndlYiIsIiRsaWJfdmVyc2lvbiI6ICIyLjI5LjEiLCJ0aW1lIjogMTYxMTU4Njk4NC45MTgsImRpc3RpbmN0X2lkIjogImFsYmFuYTE3MDhAaG90bWFpbC5kZSIsIiRkZXZpY2VfaWQiOiAiMTc3MTVhY2U0ZGEzYTctMGIyZGRjMDUzM2MzODE4LTRjM2YyMDdlLTFmYTQwMC0xNzcxNWFjZTRkYjIxMyIsIiRpbml0aWFsX3JlZmVycmVyIjogIiRkaXJlY3QiLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogIiRkaXJlY3QiLCIkdXNlcl9pZCI6ICJhbGJhbmExNzA4QGhvdG1haWwuZGUiLCJ0b2tlbiI6ICIxNDgwYjIyNDRmZGQ0ZDgyMTIyN2EyOWUyNjM3ZjkyMiJ9fQ%3D%3D&ip=1&_=1611586984918 HTTP/1.1" 200 0
[25/Jan/2021 16:03:05] "GET /app/updates_available/ HTTP/1.1" 200 22
[25/Jan/2021 16:03:05] "HEAD /directories?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Tut%20Test&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 68
[25/Jan/2021 16:03:05] "HEAD /directories?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Model%201&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 67
[25/Jan/2021 16:03:05] "POST /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Model%201&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 79
[25/Jan/2021 16:03:05] "POST /json_models?path=H:\OneDrive\Dokumente\Perceptilabs\Default/Tut%20Test&token=W0sSPzX2HdLGQntXmHIqh3sWI19mqW6O3cphcopyEdI HTTP/1.1" 200 80
2021-01-25 16:03:05,284 - INFO - server.py:191 - Frontend receiver:  , Frontend request: setUser
2021-01-25 16:03:05,285 - INFO - server.py:191 - Created coreLogic for network ''
2021-01-25 16:03:05,286 - INFO - server.py:191 - User has been set to albana1708@hotmail.de
2021-01-25 16:03:06,108 - INFO - server.py:191 - Frontend receiver: 1 , Frontend request: isTrained
2021-01-25 16:03:06,108 - INFO - server.py:191 - Created coreLogic for network '1'
2021-01-25 16:03:06,111 - INFO - server.py:191 - Frontend receiver: 2 , Frontend request: isTrained
2021-01-25 16:03:06,112 - INFO - server.py:191 - Created coreLogic for network '2'
2021-01-25 16:03:06,115 - INFO - server.py:191 - Frontend receiver: 1 , Frontend request: ScanCheckpoint
2021-01-25 16:03:06,118 - INFO - server.py:191 - Frontend receiver: 2 , Frontend request: ScanCheckpoint
2021-01-25 16:03:06,123 - INFO - server.py:191 - Frontend receiver: 1 , Frontend request: getStatus
2021-01-25 16:03:06,161 - INFO - server.py:191 - Frontend receiver: 2 , Frontend request: getStatus
2021-01-25 16:03:06,197 - INFO - server.py:191 - Frontend receiver: 1 , Frontend request: isTrained
2021-01-25 16:03:06,200 - INFO - server.py:191 - Frontend receiver: 2 , Frontend request: isTrained
2021-01-25 16:03:06,203 - INFO - server.py:191 - Frontend receiver: 1 , Frontend request: ScanCheckpoint
2021-01-25 16:03:06,206 - INFO - server.py:191 - Frontend receiver: 2 , Frontend request: ScanCheckpoint
2021-01-25 16:03:06,210 - INFO - server.py:191 - Frontend receiver:  , Frontend request: setUser
2021-01-25 16:03:06,211 - INFO - server.py:191 - User has been set to albana1708@hotmail.de
2021-01-25 16:03:09,263 - INFO - server.py:191 - Frontend receiver:  , Frontend request: getNetworkData
2021-01-25 16:03:09,384 - INFO - server.py:191 - Skipping settings recommendations for layer 1598915799200 because it has been modified by the user
2021-01-25 16:03:09,385 - INFO - server.py:191 - Skipping settings recommendations for layer 1598915800150 because it has been modified by the user
[25/Jan/2021 16:03:09] "GET /mixpanel/engage/?data=eyIkc2V0X29uY2UiOiB7IiRlbWFpbCI6ICJhbGJhbmExNzA4QGhvdG1haWwuZGUiLCIkY3JlYXRlZCI6ICIyMDIxLTAxLTI1VDE1OjAzOjA5In0sIiR0b2tlbiI6ICIxNDgwYjIyNDRmZGQ0ZDgyMTIyN2EyOWUyNjM3ZjkyMiIsIiRkaXN0aW5jdF9pZCI6ICJhbGJhbmExNzA4QGhvdG1haWwuZGUiLCIkZGV2aWNlX2lkIjogIjE3NzE1YWNlNGRhM2E3LTBiMmRkYzA1MzNjMzgxOC00YzNmMjA3ZS0xZmE0MDAtMTc3MTVhY2U0ZGIyMTMiLCIkdXNlcl9pZCI6ICJhbGJhbmExNzA4QGhvdG1haWwuZGUifQ%3D%3D&ip=1&_=1611586989896 HTTP/1.1" 200 0
[25/Jan/2021 16:03:09] "GET /mixpanel/engage/?data=eyIkc2V0IjogeyIkb3MiOiAiV2luZG93cyIsIiRicm93c2VyIjogIkZpcmVmb3giLCIkYnJvd3Nlcl92ZXJzaW9uIjogODQsIiRpbml0aWFsX3JlZmVycmVyIjogIiRkaXJlY3QiLCIkaW5pdGlhbF9yZWZlcnJpbmdfZG9tYWluIjogIiRkaXJlY3QiLCIkZW1haWwiOiAiYWxiYW5hMTcwOEBob3RtYWlsLmRlIiwiJGxhc3RfbG9naW4iOiAiMjAyMS0wMS0yNVQxNTowMzowOSJ9LCIkdG9rZW4iOiAiMTQ4MGIyMjQ0ZmRkNGQ4MjEyMjdhMjllMjYzN2Y5MjIiLCIkZGlzdGluY3RfaWQiOiAiYWxiYW5hMTcwOEBob3RtYWlsLmRlIiwiJGRldmljZV9pZCI6ICIxNzcxNWFjZTRkYTNhNy0wYjJkZGMwNTMzYzM4MTgtNGMzZjIwN2UtMWZhNDAwLTE3NzE1YWNlNGRiMjEzIiwiJHVzZXJfaWQiOiAiYWxiYW5hMTcwOEBob3RtYWlsLmRlIn0%3D&ip=1&_=1611586989895 HTTP/1.1" 200 0
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\websockets\server.py:191: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\websockets\server.py:191: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2021-01-25 16:03:09.983949: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-01-25 16:03:09.991686: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2021-01-25 16:03:10.023532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 16:03:10.027077: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\websockets\server.py:191: The name tf.global_variables_initializer is deprecated. Please use tf.compat.v1.global_variables_initializer instead.

[25/Jan/2021 16:03:10] "GET /mixpanel/decide/?verbose=1&version=3&lib=web&token=1480b2244fdd4d821227a29e2637f922&distinct_id=albana1708%40hotmail.de&ip=1&_=1611586989894 HTTP/1.1" 200 0
2021-01-25 16:03:10.190338: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 16:03:10.193263: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
WARNING:tensorflow:
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2021-01-25 16:03:11.169519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 16:03:11.173233: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
2021-01-25 16:03:11.312748: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 16:03:11.315568: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
WARNING:tensorflow:From <rendered-code: 1598982397425 [TrainNormal]>:150: DatasetV1.output_types (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(dataset)`.
WARNING:tensorflow:From <rendered-code: 1598982397425 [TrainNormal]>:150: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:347: Iterator.output_types (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_types(iterator)`.
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:348: Iterator.output_shapes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(iterator)`.
WARNING:tensorflow:From h:\anaconda\envs\pl\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py:350: Iterator.output_classes (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.Instructions for updating:
Use `tf.compat.v1.data.get_output_classes(iterator)`.
2021-01-25 16:03:11.979371: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-01-25 16:03:11.982515: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
2021-01-25 16:03:12,314 - INFO - server.py:191 - Autosettings: applied rule ProcessReshape1DFromPrimeFactors to ProcessReshapeSpec (name: Reshape_1, id: 1598915836465, type: ProcessReshape)
2021-01-25 16:03:12,315 - INFO - server.py:191 - Autosettings: applied rule DeepLearningFcOutputShapeFromLabels to DeepLearningFcSpec (name: Dense_1, id: 1598970577549, type: DeepLearningFC)
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartPic.js HTTP/1.1" 200 365
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartBase.js HTTP/1.1" 200 2403
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartBase.js HTTP/1.1" 200 2403
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartPic.js HTTP/1.1" 200 365
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartBase.js HTTP/1.1" 200 2403
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartBase.js HTTP/1.1" 200 2403
[25/Jan/2021 16:03:12] "GET /static/webworkers/calcChartBase.js HTTP/1.1" 200 2403
```

</details>

![perceptilabs_no_preview](https://user-images.githubusercontent.com/20783788/105724231-ee38df80-5f27-11eb-8e68-183458549436.PNG)

**Comment by Rolun** [comment]
Hi @Nakrum,
Thank you very much for the logs!

What setup/system are you using to run the tool?

It looks like some files are being blocked, which may cause this issue. It is reproducible by stopping the frontend server
The frontend is running on port 8080 if that helps you in any way.
