### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by GrimblyGorn** [PerceptiLabs/PerceptiLabs#90]
No matter which model template I select the final component always has an exclamation icon on it and eventually I get this error in the console.

Traceback (most recent call last):
  File "perceptilabs\lwcore\base.py", line 132, in perceptilabs.lwcore.base.LightweightCore._compute_layer_results
  File "perceptilabs\layers\helper.py", line 88, in perceptilabs.layers.helper.LayerHelper.get_class
  File "perceptilabs\layers\helper.py", line 85, in perceptilabs.layers.helper.LayerHelper.get_class
  File "perceptilabs\layers\helper.py", line 42, in perceptilabs.layers.helper.load_code_as_module
  File "perceptilabs\layers\helper.py", line 35, in perceptilabs.layers.helper._CodeLoader.exec_module
  File "<rendered-code: 1598990616678 [TrainDetector]>", line -16, in <module>

ImportError: DLL load failed: %1 is not a valid Win32 application.

It varies slightly between models but it always contains that final line about the DLL error.

I have attempted to resolve any Path issues as outlined [here](https://github.com/tensorflow/tensorflow/issues/37759) in case it has something to do with Tensorflow not being able to locate Cuda. I believe I have resolved those issues but seeing as this error is still persisting perhaps I haven't. 

Any insight on this would be highly appreciated.

**Comment by Rolun** [comment]
Hi @GrimblyGorn,
Thank you for all the details!

As you mentioned, Anaconda with Python 3.8 is fine as long as the environment is either 3.6 or 3.7.

The Atari setup does not affect the rest of the tool besides DQN (or more specifically, the TrainReinforce component), and the Mixpanel errors you are seeing are not critical errors, they won't stop anything from functioning.

The biggest clue I'm seeing is that you are running on Windows 7, it has not been tested on that version and has only been confirmed to work on Windows 10. That's not saying that it can't work, but Windows is known to give some interesting issues when going between versions. The error "ImportError: DLL load failed: %1 is not a valid Win32 application." you get also seems to point in that direction.

If you look in the code of the training component, do you see what line is giving the error?
And if that is not obvious, what do you see in the terminal when starting PerceptiLabs as "perceptilabs -v=3" and then pressing Run on one of the templates?

All the best,
Robert

**Comment by GrimblyGorn** [comment]
For the last couple of days while I've been messing with fixing this issue I've also been messing with various other GAN installations and other ML things in general since it's only recently I discovered this whole conda environment thing and that was one of the main things keeping me from experimenting with all this before cause I didn't want to completely wreck my environment to match someone else's only to find it couldn't work or something anyway and then have to fix my environment. With conda being an option now I can freely replicate these environments and then destroy them as needed so this is much more casual now. 

Anyway, having done this for a few days I started to notice my system was behaving poorly and doing weird things, for instance, the Perceptilabs website hasn't been able to load for at least the last couple of days but other sites worked fine. Most recently the Perceptilabs GUI quit working but it was inconsistent at first and then became a constant. It would seemingly fail to resolve the keycloak request it uses when loading the login screen and instead just show a blank white browser screen. There were also other weird things outside of the browser I was having trouble with and restarting the browser failed to resolve those issues so I finally saved and closed out all the other programs and things I had going and restarted the whole computer. 

After that, I came straight back to the browser and checked that the Perceptilabs website was working again and then tried launching the GUI which was also working again finally. Then I tried the GAN template and to my surprise, it did not throw the DLL error this time so I tried to Run it and that also worked for the first time ever, which was exciting to finally see. 

So, in regards to the DLL issue, I have no idea what caused it but it seems to be resolved now. It could be that the restart fixed it somehow or it could be some of the other things I was doing earlier today to fix something else I found called [StyleFlow](https://github.com/RameenAbdal/StyleFlow). That was also giving me the same DLL error and seemed to be related to OpenCV somehow so I got a fresh copy of that and had to PATH to it. While doing that I also removed some old Python 2.7 PATHS along with some SimpleCV PATHS so maybe that had something to do with this and I had fixed it before the restart but wasn't able to confirm that yet cause the browser GUI wasn't working till after the restart.

I did notice while this was Running finally that there were a lot of error readouts related to mixpanel stuff and the graphs seemed to change in bursts between the bursts of error readouts so I thought perhaps the readouts might be slowing things down somehow and I closed out everything to restart it without the verbose -v=3 readouts but I'm not sure if there's a difference in speed now that I've switched.

So the takeaway from this is that this seems to be fixed now though I'm not sure why, and now you know that this works on Windows 7 x64 :)

I've included the readout log from my quick test session with all the mixpanel errors and such in case you wanted to have a look and that. It seems to be a bunch of HTTP errors related to the mixpanel so I'm wondering if that has something to do with my firewall blocking something it shouldn't since it defaults to blocking everything. Sadly though it seems to be an incomplete log and didn't grab everything from the start of the session so I guess some was overwritten once the log got too big. I'll have to look into fixing that later as well to retain larger logs if needed. Maybe there's still something useful or interesting in there though :)

[readout-log.txt](https://github.com/PerceptiLabs/PerceptiLabs/files/5905720/readout-log.txt)

**Comment by Rolun** [comment]
Wow that's quite a trip you took @GrimblyGorn ! Glad to hear that it all started working in the end :)

As for the Mixpanel errors, they are on a separate thread from the training and are not critical, so the slowdown from those should be minimal to none.
Thanks for the log, will look through it and see if we can find anything in there.
It's likely a firewall or something as you said. Look out for anything blocking port 5000, as that is the port the Kernel is running from.

**Comment by GrimblyGorn** [comment]
I'm still having a lot of trouble with this keycloak request working and in general connecting to the PerceptiLabs website as well. The two seem to be connected. If I can't load the website the keycloak doesn't seem to work either and I can't load the GUI even though the kernel seems to be running fine. I just get a blank white browser tab with the generated address in the URL box. I don't have any trouble with any other websites so I'm really not sure what's going on now. Restarting the computer seems to be a hit or miss so I'm thinking it's just lucky timing and that it doesn't actually affect whatever is causing this connection issue. I have a lot of extensions for chrome but most aren't active for incognito mode but it does the same thing for that as well. I have basically no extensions for Opera and still, it gives me the same blank tab there as well. Chrome and Opera are both whitelisted on my firewall as are the python, pip, and perceptilabs exe files in the Miniconda environment I setup. I'm not sure what else I could whitelist that would make a difference and I'm not sure that's the issue as it does work sometimes when I'm able to load the website.

Any ideas on what might be causing this?

**Comment by Rolun** [comment]
I'm unsure about the website not working, but one thing which causes the tool frontend not to work is having one of the ports already blocked by another service.
If you notice the frontend just being white, try stopping the tool in the terminal and then checking if the ports are occupied by:
netstat -a -n -o | find "8080"
netstat -a -n -o | find "8000"
netstat -a -n -o | find "8011"
netstat -a -n -o | find "5000"

If any of those ports are occupied, try killing the process which is running on it and then re-run PerceptiLabs.

For the website, we have had some issues with people connecting to it before (although never as volatile as you seem to have it) and are changing its hosting in about a week. After that change it may work better for you.

**Comment by GrimblyGorn** [comment]
I started thinking about this more after I had posted my last comment and got to digging in Chromes settings, I believe I have identified the issue and resolved it now by changing the DNS settings in Chrome under (Settings->Security->Use Secure DNS) it was set to use the DNS settings from my service provider and I changed it to use Googles Public DNS and the website instantly started working again. Strangely changing that back or disabling it entirely doesn't seem to break my ability to connect. I think that if I left it switched back or turned off long enough it would fail again though. I'm not sure how but my service provider must not be doing a great job with DNS handling :)

I also checked the web interface and it was working again finally and has been working since then along with the website so I think it was the DNS and setting this in Chrome seems to override the computer's settings which would explain why incognito mode and Opera also suffered from this issue.

I went ahead and checked the netstat commands you listed as well but saw no blocking connections there so I think this may have been the whole issue.

I'm sorry to have wasted your time with all of these things. Maybe this can help serve as a guide to others that may encounter these same issues and help them out some. Also, perhaps when working on the new website hosting you guys can look into this DNS thing as well so more people can connect, even from janky DNS providers :)

**Comment by Rolun** [comment]
Great to hear that you found the issue @GrimblyGorn ! :)
And thanks for the detailed information, it'll be very useful for us for the new website
